background = #3B4349
foreground = #BFBBBB

selection-background = #3F4347
selection-foreground = #BFBBBB

cursor-color = #CA9CAA

palette = 0=#3F4347
palette = 1=#584F4F
palette = 2=#9C7690
palette = 3=#6A859F
palette = 4=#8C9381
palette = 5=#E599B1
palette = 6=#9FD0A6
palette = 7=#8A8585
palette = 8=#615D5D
palette = 9=#584F4F
palette = 10=#9C7690
palette = 11=#6A859F
palette = 12=#8C9381
palette = 13=#E599B1
palette = 14=#9FD0A6
palette = 15=#8A8585
