background = #0A0D09
foreground = #B1B5B1

selection-background = #35322D
selection-foreground = #B1B5B1

cursor-color = #A0A972

palette = 0=#35322D
palette = 1=#525C52
palette = 2=#785E56
palette = 3=#817C72
palette = 4=#CD5D36
palette = 5=#8F9D33
palette = 6=#DAC6A9
palette = 7=#878D86
palette = 8=#5E635E
palette = 9=#525C52
palette = 10=#785E56
palette = 11=#817C72
palette = 12=#CD5D36
palette = 13=#8F9D33
palette = 14=#DAC6A9
palette = 15=#878D86
