# APPLICATION KEYBINDINGS

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod SHIFT, RETURN, exec, [float; size 800 450; center] $terminal
bind = $mainMod, E, exec, $terminal -e yazi
bind = $mainMod, W, exec, $browser
bind = $mainMod, M, exec, spotify
bind = $mainMod, C, exec, /home/ravn/.local/bin/zed
bind = $mainMod, SPACE, exec, pgrep wofi || $launcher
bind = $mainMod SHIFT, A, exec, ~/.config/scripts/utils/util-launcher.sh
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod, Escape, exec, pgrep wlogout || wlogout -b 2
bind = $mainMod SHIFT, P, exec, hyprpicker -a
bind = $mainMod SHIFT, W, exec, waytrogen
bind = $mainMod ALT, W, exec, pgrep -x waybar >/dev/null && killall waybar || waybar &
bind = $mainMod ALT, B, exec, bongocat -c ~/.config/bongocat/bongo.conf --toggle
bind = $mainMod ALT, N, exec, ~/.config/scripts/restart-swaync.sh
