# Hyprland with colors from wallust
# You can use this template by adding the following to wallust.toml:
# hypr = { src = "hyprland.conf", dst = "~/.config/hypr/colors.conf" }
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    col.active_border = rgb(817C72) rgb(CD5D36) rgb(8F9D33) rgb(DAC6A9) rgb(785E56)
    col.inactive_border = rgba(0A0D09ee)
}
