# Hyprland with colors from wallust
# You can use this template by adding the following to wallust.toml:
# hypr = { src = "hyprland.conf", dst = "~/.config/hypr/colors.conf" }
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    col.active_border = rgb(6A859F) rgb(8C9381) rgb(E599B1) rgb(9FD0A6) rgb(9C7690)
    col.inactive_border = rgba(3B4349ee)
}
