source = $HOME/.config/hypr/config/variables.conf

# FLOATING WINDOW RULES
windowrule = float class:^(xdg-desktop-portal-gtk)$
windowrule = float class:^($terminal)$ title:^(top)$
windowrule = float class:^($terminal)$ title:^(btm)$
windowrule = float class:^($terminal)$ title:^(htop)$
windowrule = float size 1200 780 class:^($terminal)$ title:^(btop)$
windowrule = float class:^(thunar)$ title:^(Rename.*)$
windowrule = float class:^(Thunar)$ title:^(Rename.*)$
windowrule = float class:^(org.gnome.FileRoller)$
windowrule = float class:^(qt5ct)$
windowrule = float class:^(qt6ct)$
windowrule = float class:^(nwg-look)$
windowrule = float class:^(nwg-displays)$
windowrule = float class:^(org.pulseaudio.pavucontrol)$
windowrule = float class:^(blueman-manager)$
windowrule = float class:^(nm-connection-editor)$
windowrule = float class:^(org.Waytrogen.Waytrogen)$
windowrule = float class:^(waytrogen)$
windowrule = float class:^(com.github.unrud.VideoDownloader)$
windowrule = float class:^(com.interversehq.qView)$