source = $HOME/.config/hypr/config/variables.conf

# PICTURE-IN-PICTURE (PIP) RULES
windowrule = float class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = pin class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = size 480 270 class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).*
# windowrule = noblur class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).* # rule type removed in 0.55.4
windowrule = move 74.5% 4.25% class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = animation slide class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = opaque class:(firefox|google-chrome|zen) title:.*(Picture-in-Picture|Picture in Picture).*

# Image viewer Qview
windowrule = opaque class:(com.interversehq.qView)